name: test-workflow
on: merge
  push:
    branches:
      - master

jobs:
  job1:
    name: job-1
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        run: |
          echo test 1
          echo test 2